interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [ ".",
]

[[modules ]]
path = "src"
depends_on = ["src.RaspberryPi.SharedMemory"]

[[modules ]]
path = "src.RaspberryPi.Socket"
depends_on = ["src.RaspberryPi.InternalException"]

[[modules ]]
path = "src.RaspberryPi.jps"
depends_on = []

[[modules ]]
path = "src.RaspberryPi.States"
depends_on = []

[[modules ]]
path = "src.main"
depends_on = ["src.LiDAR.build.RunLiDAR", "src.Arduino.ArduinoUno", "src.RaspberryPi.InternalException", "src.RaspberryPi.Socket", "src.RaspberryPi.SharedMemory", "src.RaspberryPi.States", "src.RaspberryPi.point_selection"]

[[modules ]]
path = "src.RaspberryPi.BCI.bci_essentials_wrapper"
depends_on = ["src.RaspberryPi.InternalException", "src"]

[[modules ]]
path = "src.LiDAR.build.RunLiDAR"
depends_on = []

[[modules ]]
path = "src.RaspberryPi.InternalException"
depends_on = []

[[modules ]]
path = "src.Arduino.ArduinoUno"
depends_on = ["src.RaspberryPi.InternalException"]

[[modules ]]
path = "src.RaspberryPi.SharedMemory"
depends_on = ["src.RaspberryPi.States", "src.RaspberryPi.InternalException", "src.Arduino.ArduinoUno"]

[[modules ]]
path = "src.RaspberryPi.point_selection"
depends_on = ["src.RaspberryPi.InternalException"]
