# pragma once
# ifndef PROGRAM_CONSTANTS
# define PROGRAM_CONSTANTS

# define FREQUENCIES (float[]){ 7.5f, 8.57f, 10.0f, 12.0f }
# define FILTER_STABILIZATION_DELAY 5.0f

# define TRIAL_COUNT 4
# define STIMULUS_DURATION 6.0f
# define BREAK_DURATION 3.0f

# define SELECTION_DISPLAY_THRESHOLD 0.95f

# define CONNECTION_ATTEMPT_INTERVAL 0.5f

# endif