include_guard(GLOBAL)

set(CONFIGURATION_PATH_SUFFIX_EXPRESSION "$<$<BOOL:${CMAKE_CONFIGURATION_TYPES}>:/$<CONFIG>>")
set(FULL_RUNTIME_OUTPUT_PATH_EXPRESSION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}${CONFIGURATION_PATH_SUFFIX_EXPRESSION}")